#!/bin/bash
# helper script for conversion from SVG into PNG (some another output formats can work too)
# tested with Gimp 2.4.5

if [[ "x$2" == "x" ]] ; then
	echo "$0 <infile.svg> <outfile.png>"
	exit 1
fi

# resolution used for conversion
dpi="86"

outfile="$2"
infile="$1"

script=`cat <<EOF
(let* 
	(
		(img (car (file-svg-load RUN-NONINTERACTIVE "$infile" "" $dpi 0 0 0 )))
		(drawable (car (gimp-layer-new img 100 100 RGB-IMAGE "bkg" 100 NORMAL)))
	) 
	(gimp-image-add-layer img drawable 0)
	(gimp-image-lower-layer img drawable)
	(gimp-layer-resize-to-image-size drawable)

	(gimp-edit-fill drawable WHITE-FILL)
    
	(gimp-selection-none img)

	(let* 
		(
			(layer-to-save (car (gimp-image-merge-visible-layers img 0)))
		)
		(gimp-file-save RUN-NONINTERACTIVE img layer-to-save "$outfile" "$outfile")
	)

	(gimp-image-delete img)
	(gimp-quit 0)
)
EOF`

# WITH usage of svg2png.scm in ~/.gimp-xxx/scripts directory
# gimp -i -b "(svg2png \"$1\" \"$2\" $dpi)" -b "(gimp-quit 0)"

# WITHOUT usage of svg2png.scm in ~/.gimp-xxx/scripts directory
gimp -i -b "${script}" -b "(gimp-quit 0)"

